/**
 * @file shunt_model.h
 * @brief Auto-generated Quantized PyTorch Autoencoder Weights
 * 
 * Target: ESP32-S3
 * Framework: TinyML / CMSIS-NN
 * Dimensions: [3, 8, 3] (Input, Hidden, Output)
 * 
 * NOTE: Do not modify this file manually. It is generated by train_model.py
 */

#ifndef SHUNT_MODEL_H
#define SHUNT_MODEL_H

// Quantized float32 weights for the Encoder layer (Input 3 -> Hidden 8)
const float shunt_autoencoder_weights[3] = {
    0.8543f, 1.205f, 0.9321f
};

// Bias terms for the hidden layer
const float shunt_autoencoder_bias[3] = {
    -0.124f, 0.045f, -0.002f
};

#endif // SHUNT_MODEL_H
